title: Michael Jae-Yoon Chung
email: mjyc@cs.washington.edu
description: ""
baseurl: "/~mjyc" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mjyc_
github_username: mjyc
google_analytics: "UA-142528997-1"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - index.md
  - research.md
  - teaching.md
  - blog.md

# jekyell-scholar settings
scholar:
  bibliography_template: "bib"
  repository: "/assets/pdfs"
  sort_by: "year,month"
  order: "descending"
